### ISSUE TITLE
Error: STATUS_ACCESS_DENIED (0xC0000022)  in readFile

### ISSUE THREAD

**Issue by anilomanwar** [bchelli/node-smb2#31] opened 2018-11-22 01:40 UTC
> I am able to access the files using readdir but readFile is giving error

Code Used -- 
```
// load the library
 var SMB2 = require('smb2');
 
// create an SMB2 instance
var smb2Client = new SMB2({
  share:'\\\\<server>\\share$'
, domain:'<mydomain>'
, username:'<myusername>'
, password:'<mypassword>'
});

```

 smb2Client.readdir('classS1\\Files', function(err, files){
       if(err) throw err;
    
    console.log(files)
    for (var i=0;i<10;i++)
    {
        smb2Client.readFile('classS1\\Files\\'+files[i], function(err, data){
            if(err) throw err;
            console.log(data)
        });
    }

Error --
Error: STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights.
    at Object.08000000 (c:\Anil\Test4SMB2\node_modules\smb2\lib\tools\message.js:25:21)
    at Socket.<anonymous> (c:\Anil\Test4SMB2\node_modules\smb2\lib\tools\smb2-forge.js:72:31)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)

**Comment by bchelli** [comment] 2018-11-22 06:02
Hi @anilomanwar 

I just ran the following code:
```javascript
// load the library
var SMB2 = require('smb2');
 
// create an SMB2 instance
var smb2Client = new SMB2({
	share:'\\\\<server>\\share$',
	domain:'<mydomain>',
	username:'<myusername>',
	password:'<mypassword>'
});

smb2Client.readdir('classS1\\Files', function(err, files){
	if(err) {
		throw err;
	}

	console.log(files);

	for (var i=0; i<files.length; i++) {
		console.log(files[i]);
		smb2Client.readFile('classS1\\Files\\'+files[i], function(err, data){
			if(err) throw err;
			console.log(data)
		});
	}
});
```

And got it to work properly, here is what is displayed in the console:
```
[ '1.txt', '2.txt', '3.txt' ]
1.txt
2.txt
3.txt
<Buffer 6f 6e 65>
<Buffer 74 77 6f>
<Buffer 74 68 72 65 65>
```

I also checked the result with folders (New folder) and got the following result, without error:
```
[ '1.txt', '2.txt', '3.txt', 'New folder' ]
1.txt
2.txt
3.txt
New folder
<Buffer >
<Buffer 6f 6e 65>
<Buffer 74 77 6f>
<Buffer 74 68 72 65 65>
```

My best guess is that you do have a permission issue as said in the error message: `{Access Denied} A process has requested access to an object but has not been granted those access rights.`

Using Windows' File Explorer, could you check that you have the proper permission to access this folder?

Thanks,

**Comment by anilomanwar** [comment] 2018-11-22 06:11
Yes, I have access to that folder.

I am able to list all the files from that folder but not able to open the file.

I am reading .pdf file hope it's not related to the file type

**Comment by bchelli** [comment] 2018-11-27 19:18
> I am able to list all the files from that folder but not able to open the file.

Are you able to list all the files from that folder when using SMB?

Meaning can you list the files if from the windows explorer you go to:
`\\<server>\share$\classS1\Files`

Thanks,

**Comment by anilomanwar** [comment] 2018-11-28 01:44
Yes, you are correct I can list those files but getting issues while reading individual file

**Comment by bchelli** [comment] 2018-11-30 19:33
Thanks for your response.
So it looks like this is a permission issue on the server, closing this thread.

Let me know if I can help with anything else

Best

**Closed as completed by bchelli** 2018-11-30 19:33 UTC

**Comment by alexfbs** [comment] 2019-07-05 14:17
Hello, @bchelli 

I like this library so much, it's very helpful to me! 😃 

I have noticed the same issue though trying to read a file from a read-only directory.

The way to reproduce the issue:
1. Share a folder with read-only permission.
2. Run the following code (the same as above):
```javascript
// load the library
var SMB2 = require('smb2');
 
// create an SMB2 instance
var smb2Client = new SMB2({
	share:'\\\\<server>\\share$',
	domain:'<mydomain>',
	username:'<myusername>',
	password:'<mypassword>'
});

smb2Client.readdir('classS1\\Files', function(err, files){
	if(err) {
		throw err;
	}

	console.log(files);

	for (var i=0; i<files.length; i++) {
		console.log(files[i]);
		smb2Client.readFile('classS1\\Files\\'+files[i], function(err, data){
			if(err) throw err;
			console.log(data)
		});
	}
});
```

It throws a 'STATUS_ACCESS_DENIED' error.

**Readdir** function works fine as well as **readfile** from a folder with _full access_ permissions.

I suspect **'DesiredAccess':0x001701DF** line from [lib/messages/open.js](https://github.com/bchelli/node-smb2/blob/master/lib/messages/open.js) file:
```javascript
    return new SMB2Message({
      headers:{
        'Command':'READ'
      , 'SessionId':connection.SessionId
      , 'TreeId':connection.TreeId
      , 'ProcessId':connection.ProcessId
      }
    , request:{
        'Buffer':buffer
      , 'DesiredAccess':0x001701DF
      , 'NameOffset':0x0078
      , 'CreateContextsOffset':0x007A+buffer.length
      }
    });
```

Once it is commented out the problem is gone.

Regards, Alex.

**Comment by lkiii** [comment] 2019-07-30 07:51
Hello, I can confirm @alexfbs case. I have reproduced the issue on read only files and commenting `, 'DesiredAccess':0x001701DF` line fixed the issue.

The issue should be reopened.

**Comment by jokecamp** [comment] 2019-08-28 18:28
There is a fork commit that shows appropriate hex values. 

`https://github.com/Node-SMB/marsaud-smb2/commit/2307e97cc230ae4d828215e3708c7ef890cd6e31`

**Comment by lkiii** [comment] 2019-09-22 21:37
@jokecamp thank you, I have switched to this fork
