### ISSUE TITLE
asynchronous readFile issue

### ISSUE THREAD

**Issue by bvankeir** [bchelli/node-smb2#13] opened 2016-01-20 15:43 UTC
I'm trying to read a bunch of files in parallel, but concurrent access seems to cause problems.

With following code one could test: set up the options for your share, and adapt the files array. With just one item in the array, all works fine, with more than one I get 'connect EINVAL'.

``` javascript
var smb2 = require('smb2');
var options = {
  share: '***',
  domain: '',
  username: '***',
  password: '***',
  autoCloseTimeout: 0
};

var files = ['file1', 'file2'];

smbclient = new smb2(opts);

var readyCounter = files.length;
for(var i in files){
  //get the file
  (function(index){
    try{
      smbclient.readFile(files[index], {encoding: null}, function(err, data){
        if(err){
          console.log('Error reading file ' + files[index] + ': ' + err.message);
        } else {
          //data contains the raw data from the file --> parse it
          parse(index, data);
          readyCounter--;
          if(readyCounter == 0){
            console.log('ALL FILES READ');
            smbclient.close();
          }
        }
      });
    } catch(e){
      console.log(e);
    }
  })(i);
}


function parse(index, data){
  console.log('file ' + index + ' ready');
}
```

**Comment by bvankeir** [comment] 2016-01-20 15:46
Currently, I circumvent this issue by sequentially handling file after file in the callback of the readFile function, however, true asynchronous file handling would be favourable.

**Comment by bchelli** [comment] 2018-10-04 04:16
can't reproduce, closing this issue

**Closed by bchelli** 2018-10-04 04:16 UTC
